repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: check-added-large-files
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: local
    hooks:
    -   id: c-codebase-checker
        name: Compile all C files
        files: \.c$
        entry: python c-codechecker.py
        pass_filenames: true
        language: system
    -   id: latex-checker
        name: Compile main.tex
        entry: pdflatex main.tex
        pass_filenames: false
        language: system
